# Generated by Django 3.1.2 on 2021-08-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
    ]
