# Generated by Django 3.1.2 on 2021-07-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Icat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Lcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Scat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Skillcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1500)),
                ('education', models.CharField(blank=True, default='', max_length=1700, null=True)),
                ('experience', models.CharField(blank=True, default='', max_length=130, null=True)),
                ('industry', models.CharField(blank=True, default='', max_length=1200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=1200, null=True)),
                ('recruiter', models.CharField(max_length=450)),
                ('contact', models.TextField()),
                ('payrate', models.CharField(blank=True, default='', max_length=1500, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('skills', models.CharField(blank=True, default='', max_length=1200, null=True)),
                ('ecat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.ecat')),
                ('icat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.icat')),
                ('lcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.lcat')),
                ('scat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.scat')),
                ('skillcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.skillcat')),
            ],
        ),
    ]
