# Generated by Django 3.1.2 on 2021-07-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='ecat',
        ),
        migrations.RemoveField(
            model_name='job',
            name='icat',
        ),
        migrations.RemoveField(
            model_name='job',
            name='lcat',
        ),
        migrations.RemoveField(
            model_name='job',
            name='scat',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skillcat',
        ),
        migrations.DeleteModel(
            name='Ecat',
        ),
        migrations.DeleteModel(
            name='Icat',
        ),
        migrations.DeleteModel(
            name='Lcat',
        ),
        migrations.DeleteModel(
            name='Scat',
        ),
        migrations.DeleteModel(
            name='Skillcat',
        ),
    ]
