# Generated by Django 3.1.2 on 2021-07-30 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210730_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, default='', max_length=17000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=120000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='', max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.CharField(blank=True, default='', max_length=4500, null=True),
        ),
    ]
