# Generated by Django 3.1.2 on 2021-08-04 10:40

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210730_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='Duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='apply_by',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_description',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(default=0, upload_to='upload/company_profile/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_details',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Internship'), ('Internship', 'Internship'), ('Part-Time', 'Part-Time')], default=0, max_length=150),
            preserve_default=False,
        ),
    ]
