# Generated by Django 3.1.2 on 2021-08-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210801_2254'),
        ('job', '0004_auto_20210804_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
    ]
