# Generated by Django 3.1.2 on 2021-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210801_2254'),
        ('job', '0007_auto_20210804_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Profile'),
        ),
    ]
