# Generated by Django 3.1.2 on 2021-08-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20210806_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='user',
            new_name='author',
        ),
    ]
