# Generated by Django 3.1.2 on 2021-08-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210801_2254'),
        ('job', '0010_auto_20210806_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
