# Generated by Django 3.1.2 on 2021-08-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0011_auto_20210806_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='author',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
