# Generated by Django 3.1.2 on 2021-08-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20210807_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applicants',
        ),
    ]
